### ISSUE TITLE
Kapitola metody, nefungujici odkaz v bonusu na predchozi cviceni

### ISSUE THREAD

**Issue by andywaltlova** [Czechitas-Python/uvod-do-progr-2#103]
https://kodim.cz/programovani/uvod-do-progr-2/uvod-do-programovani-2/slicing-metody-moduly/metody/chytrejsi-cisla-jako-text

Jenom si to tady poznacim

**Comment by ZelenyMartin** [comment]
Navrhuji to bonusové cvičení smazat.

**Comment by andywaltlova** [comment]
Myslim ze by klidne mohla byt ta zminka o tom ze to jde na jeden radek v tom cviceni na ktere se odkazuje bonus, na konci toho reseni, protoze tz kroky uz tam jsou rozepsane.
