### ISSUE TITLE
Drobne preklepy v textu

### ISSUE THREAD

**Issue by pavelsuk** [Czechitas-Python/uvod-do-progr-2#107]
Prochazel jsem si podklady na zitrejsi celodenni lekci (lektor @ZelenyMartin )

- [Co všechno už umíme](https://kodim.cz/czechitas/uvod-do-progr-2/uvod-do-programovani-2/uvod/uvod)
- [Slicing, metody, moduly](https://kodim.cz/czechitas/uvod-do-progr-2/uvod-do-programovani-2/slicing-metody-moduly/slicing)
- [Vlastní funkce](https://kodim.cz/czechitas/uvod-do-progr-2/uvod-do-programovani-2/vlastni-funkce/funkce)

a nasel jsem tam par drobnych preklepu. Hodim k tomu rovnou PR, jenom nechavam na @ZelenyMartin jestli to chce integrovat hned, nebo radeji po lekci. Nic z toho neni kriticke.

**Comment by ZelenyMartin** [comment]
Resolved in #108
