### ISSUE TITLE
Nekompletni nadpisy v kapitole o tridach

### ISSUE THREAD

**Issue by andywaltlova** [Czechitas-Python/uvod-do-progr-2#12]
Ahoj, nejsem si jista jak se z materialu v repozitari tvori webove stranky, ale v [kapitole o tridach](https://kodim.cz/kurzy/uvod-do-progr-2/uvod-do-programovani-2/tridy) jsou dva stejne nadpisy protoze se nezobrazuje ten kousek co je v nadpise jako kod :) Je to mirne matouci kdyz jsou ted dva ty nadpisy stejne -> spatne se v tom naviguje.

![Screenshot from 2022-10-11 15-47-09](https://user-images.githubusercontent.com/19702477/195108791-e13b9929-db35-4113-b885-07580c6b1811.png)

Nemam problem s tim ze by se proste do nadpisu hodila nenaformtovana verze, cimz by se mela ta navigace fixnout, ale jestli mate lepsi napad :)

**Comment by ZelenyMartin** [comment]
Issue je zalogovano u CMS: https://github.com/podlomar/kodim.cz/issues/34. @podlomar to uznal jako bug a rikal, ze to opravi.

**Comment by ZelenyMartin** [comment]
Vyřešeno v https://kodim.cz/changelog/#v1.5.10
