### ISSUE TITLE
Chyba odsazení v kapitole Dědičnost

### ISSUE THREAD

**Issue by AnetaPopelova** [Czechitas-Python/uvod-do-progr-2#13]
V posledním příkladu u metody `cerpej_dovolenou` je špatné odsazení podmínky. 

https://github.com/Czechitas-Python/uvod-do-progr-2/blob/main/uvod-do-programovani-2/dedicnost/dedicnost.md

@pesikj

**Comment by ZelenyMartin** [comment]
Fixnuto v novem repu: https://github.com/Czechitas-Python/python-oop/blob/main/dedicnost/dedicnost.md?plain=1#L74

OOP kapitoly budou z UdP2 odstraneny.
