### ISSUE TITLE
Kapitola finanční vyrovnání

### ISSUE THREAD

**Issue by pesikj** [Czechitas-Python/uvod-do-progr-2#42]
Navrhuji odebrat kapitolu finanční vyrovnání nebo přidat odkaz na zadání příkladu v ÚdP1 (pak ale bychom tam ten příklad měli nechat).

https://kodim.cz/kurzy/uvod-do-progr-2/uvod-do-programovani-2/slovniky/cteni-na-doma-financni-vyrovnani

**Comment by pesikj** [comment]
@ZelenyMartin @lutydlitatova

**Comment by ZelenyMartin** [comment]
Toto souvisi s https://github.com/Czechitas-Python/uvod-do-progr-1/issues/12

Navrhuji cele toto tema odstranit z UdP1 a zadani presunout sem. To reseni v UdP1 bez slovniku je podle me dost neoptimalni [1]. Mne se docela libi, ze netrivialni zadani je v textu rozpracovano a nechano na dokonceni za ukol.

[1] https://kodim.cz/kurzy/uvod-do-progr-1/prvni-krucky/problem-spolubydleni/problem-spolubydleni

**Comment by ZelenyMartin** [comment]
Vyreseno v #44
