### ISSUE TITLE
Nejjednodušší cvičení přesunout na první stránku

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/uvod-do-progr-2#78]
Cvičení na vstup/výstup, proměnné a výpočty:

* [Zvýšení hodnoty proměnné](https://kodim.cz/kurzy/uvod-do-progr-2/uvod-do-programovani-2/uvod/priklady#excs%3Ezvetseni-promenne)
* [Zvýšení hodnoty načtené ze vstupu od uživatele](https://kodim.cz/kurzy/uvod-do-progr-2/uvod-do-programovani-2/uvod/priklady#excs%3Ezvetseni-promenne-2)
* bonus [Fahrnheit vs. Celsius](https://kodim.cz/kurzy/uvod-do-progr-2/uvod-do-programovani-2/uvod/priklady#excs%3Efahrnheit-vs-celsius)

přesunout hned na konec první stránky opakování [Úvod, proměnné a hodnoty](https://kodim.cz/kurzy/uvod-do-progr-2/uvod-do-programovani-2/uvod/uvod). Bude tam dříve hands-on cvičení a první opakovací blok výkladu nebude tak dlouhý.

**Comment by pesikj** [comment]
Souhlasím.
