### ISSUE TITLE
Nepresnost v zadani cviceni "Cisla jako text"

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/uvod-do-progr-2#84]
https://github.com/Czechitas-Python/uvod-do-progr-2/blob/7279e490bde82a0eb4bb2e0a95c26859ff6822a9/uvod-do-programovani-2/slicing-metody-moduly/excs/cisla-jako-text.md?plain=1#L6-L10

Zmenit "desetinných" na "celých".

**Comment by pesikj** [comment]
Souhlasím.
