### ISSUE TITLE
Revize kap. Vlastní funkce

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/uvod-do-progr-2#85]
https://github.com/Czechitas-Python/uvod-do-progr-2/blob/7279e490bde82a0eb4bb2e0a95c26859ff6822a9/uvod-do-programovani-2/vlastni-funkce/funkce.md?plain=1#L21-L23

https://github.com/Czechitas-Python/uvod-do-progr-2/blob/7279e490bde82a0eb4bb2e0a95c26859ff6822a9/uvod-do-programovani-2/vlastni-funkce/funkce.md?plain=1#L36-L38

Psat vzdy dva prazdne radky po definici funkce (PEP8)

https://github.com/Czechitas-Python/uvod-do-progr-2/blob/7279e490bde82a0eb4bb2e0a95c26859ff6822a9/uvod-do-programovani-2/vlastni-funkce/funkce.md?plain=1#L62

Nevhodna ukazka - `sum` je funkce.

https://github.com/Czechitas-Python/uvod-do-progr-2/blob/7279e490bde82a0eb4bb2e0a95c26859ff6822a9/uvod-do-programovani-2/vlastni-funkce/funkce.md?plain=1#L74-L80

Zminit rizika globalnich promennych.

Doporučená struktura skriptu:
1. Hlavička - komentář co skript dělá a kdo je autorem
2. importy
3. definice funkcí
4. hlavní kód, který funkce volá

**Comment by pesikj** [comment]
Souhlasím.
