### ISSUE TITLE
Revize kap. Slovniky

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/uvod-do-progr-2#86]
Navrhuji ukazky zjednodusit a pouzit jen f-stringy

https://github.com/Czechitas-Python/uvod-do-progr-2/blob/7279e490bde82a0eb4bb2e0a95c26859ff6822a9/uvod-do-programovani-2/slovniky/slovniky.md?plain=1#L54

Vhodnejsi jsou f-stringy

https://github.com/Czechitas-Python/uvod-do-progr-2/blob/7279e490bde82a0eb4bb2e0a95c26859ff6822a9/uvod-do-programovani-2/slovniky/slovniky-a-cykly.md?plain=1#L37

https://github.com/Czechitas-Python/uvod-do-progr-2/blob/7279e490bde82a0eb4bb2e0a95c26859ff6822a9/uvod-do-programovani-2/slovniky/slovniky-a-cykly.md?plain=1#L47

Smazat a nechat jen ukazku f-stringu

**Comment by pesikj** [comment]
Souhlasím.
