### ISSUE TITLE
Nahradit kapitolu o lambda výrazech

### ISSUE THREAD

**Issue by pesikj** [Czechitas-Python/uvod-do-progr-2#9]
Nahradit kapitolu o lambda výrazech a místo ní přidat odkaz na list comprehension, který je popsaný v DA.
Důvody:
- návaznost na DA
- je to rychlejší a asi i jednodušší pro začátečníky

@ZelenyMartin @lutydlitatova

**Comment by pesikj** [comment]
Text o lambda výrazech může být potenciálně přidán jako samostatná bonusová kapitola a použit v nějakém pokročilejším kurzu.

**Comment by ZelenyMartin** [comment]
Pokud se jedna to toto cteni na doma [1], tak uz to je trochu pokrocilejsi, takze to klidne muzem dat nekam jinam. Na druhou stranu bych byl ale hodne opratrny s tim cokoliv duplikvat, tzn. proc sem pridavat list comprehension, kdyz uz je v DA a muzou si ho doma precist z toho kurzu? Python ma spoustu uzitecnych veci, krome tohoto i treba `map()`, `all()`, `any()`. Ale je otazka, jestli musime pokryt uplne vsechno, protoze v jinych zdrojich na internetu je toho taky dost.

[1]  https://kodim.cz/kurzy/uvod-do-progr-2/uvod-do-programovani-2/slovniky/cteni-na-doma-filter

**Comment by pesikj** [comment]
Jo, můžeme to vyřešit odkazem, souhlasím.

**Comment by ZelenyMartin** [comment]
List comprehension je v bonusech "Cykly 2" [1]. Já osobně bych to tam nechal jen pro ty nejzvídavější a jinak ignoroval.

Navrhuji issue uzavřít.

[1] https://kodim.cz/kurzy/uvod-do-progr-2/bonusy/cykly-2/list-comprehension
